In [3]:
import boto3
import pandas as pd; pd.set_option('display.max_columns', 100)
import numpy as np 

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score

s3 = boto3.resource('s3')
bucket_name = "rachaeld-data445"
bucket = s3.Bucket(bucket_name)

file_key = 'framingham.csv'

bucket_object = bucket.Object(file_key)
file_object = bucket_object.get()
file_content_stream = file_object.get('Body')

#reading the data-file
heart = pd.read_csv(file_content_stream)
heart.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [4]:
# removing observations with NA
heart = heart.dropna()

In [5]:
# defining the input and target variables
X = heart[['age', 'currentSmoker','totChol', 'BMI', 'heartRate']]
Y = heart['TenYearCHD']

# splitting the data
X_train, X_test, Y_train, Y_test = train_test_split( X, Y, test_size = .2)

In [11]:
# building the logistic model 
logit_md = LogisticRegression().fit(X_train, Y_train)

# predicting on the test dataset
logit_pred = logit_md.predict_proba(X_test)[:,1]
logit_pred

array([0.0922781 , 0.06721144, 0.08223888, 0.11314576, 0.05799692,
       0.47827737, 0.10026531, 0.40589831, 0.25262099, 0.38597095,
       0.11296363, 0.07374931, 0.08444314, 0.27718716, 0.115744  ,
       0.16630623, 0.0852398 , 0.12665866, 0.11028481, 0.16447406,
       0.16981925, 0.09473002, 0.12315517, 0.06107097, 0.42654933,
       0.2874943 , 0.25512967, 0.07018721, 0.0974578 , 0.2442753 ,
       0.0994979 , 0.25649385, 0.06240621, 0.15669428, 0.2380939 ,
       0.19783186, 0.09773304, 0.11103643, 0.17589303, 0.11207297,
       0.06687039, 0.0828264 , 0.08115173, 0.13142836, 0.05923888,
       0.26011322, 0.09798901, 0.29104399, 0.08927712, 0.04530038,
       0.46213565, 0.17777753, 0.14923544, 0.33481864, 0.05888636,
       0.39422036, 0.13210429, 0.28383853, 0.10297642, 0.27198775,
       0.36024904, 0.10996365, 0.03741227, 0.2765075 , 0.21521271,
       0.12363659, 0.0484903 , 0.13248531, 0.15517489, 0.05458334,
       0.2684776 , 0.1849069 , 0.13707752, 0.30958659, 0.18595

In [12]:
# changing likelihoods to labels
logit_label = np.where(logit_pred < .25, 0,1)

logit_label

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,

In [13]:
# constructing the confusion matrix
confusion_matrix(Y_test, logit_label)

array([[533, 100],
       [ 67,  32]])

In [14]:
# computing the accuracy
accuracy_score(Y_test, logit_label)

0.7718579234972678